version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: crud_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crud_db
      SPRING_DATASOURCE_USERNAME: crud_user
      SPRING_DATASOURCE_PASSWORD: yourpassword
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./crud_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge